### ISSUE TITLE
Failed to create stream reader: entry not found

### ISSUE THREAD

**Issue by trackroute** [liftbridge-io/liftbridge#28]
I just ran the go-liftbridge "Basic Usage" example against a local 1 node liftbridge server and then tried to push some messages to it using:

```
func main() {
	nc, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()
	// Simple Publisher
	for i := 0; i < 1000000; i++ {
		if err := nc.Publish("foo", []byte(fmt.Sprintf("Hello World %v", i))); err != nil {
			log.Fatal(err)
		}
	}
	if err := nc.Flush(); err != nil {
		log.Fatal(err)
	}
}
```

After around 300000 messages the go-liftbridge example panicked with "panic: rpc error: code = Unknown desc = entry not found".

I suspect this is actually an issue with the liftbridge server, not go-liftbridge because if I try to re-run the go-liftbridge example again (after it panics) the server shows the following 

> ERRO[2018-09-03 12:56:27] api: Failed to subscribe to stream [subject=foo, name=foo-stream]: rpc error: code = Internal desc = Failed to create stream reader: entry not found

Is this a bug or am I missing something somewhere?

**Comment by tylertreat** [comment]
Thanks, I will see if I can reproduce.

**Comment by tylertreat** [comment]
I've reproduced the issue. Working on tracking down the root cause. Will let you know when it's fixed.

**Comment by tylertreat** [comment]
@trackroute This should be fixed with https://github.com/liftbridge-io/liftbridge/pull/29. I've verified the problem no longer occurs. LMK if you hit any problems.

**Comment by aversant** [comment]
@trackroute  I still reproduce this situation. On 1 node liftbridge server (master branch) and config with:

```
logging:
    level: debug
    raft: true
streams:
    compact.enabled: true
    retention.max:
        age: 1h
cursors:
    stream.partitions: 1
```


1) Create stream `test-stream2` with default settings
```
time="2020-10-08 01:54:25" level=debug msg="api: CreateStream [name=test-stream2, subject=test-stream2, partitions=1, replicationFactor=1]"
time="2020-10-08 01:54:25" level=debug msg="Server becoming leader for partition [subject=test-stream2, stream=test-stream2, partition=0], epoch: 155"
 time="2020-10-08 01:54:25" level=debug msg="Updated log leader epoch. New: {epoch:155, offset:-1}, Previous: {epoch:0, offset:-1} for log [subject=test-stream2, stream=test-stream2, partition=
 time="2020-10-08 01:54:25" level=debug msg="fsm: Created stream [name=test-stream2, subject=test-stream2, partitions=1]"

```
2) Subscribe on stream:

```
time="2020-10-08 01:54:31" level=debug msg="api: Subscribe [stream=test-stream2, partition=0, start=OFFSET, offset=0, timestamp=0]"
```
3) Publish some messages:

```
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
time="2020-10-08 01:55:10" level=debug msg="api: Publish [stream=test-stream2, partition=0]"
```

Retention log by `Age 1h`:
```
time="2020-10-08 01:59:25" level=debug msg="Cleaning log /var/lib/liftbridge/streams/test-stream2/0 based on retention policy {Bytes:0 Messages:0 Age:1h0m0s}"
time="2020-10-08 01:59:25" level=debug msg="Removed earliest 0 entries from leader epoch cache based on passed offset 0 leaving 1 in epoch file for log [subject=test-stream2, stream=test-strea
.....
time="2020-10-08 02:59:25" level=debug msg="Appending new log segment for /var/lib/liftbridge/streams/test-stream2/0 with base offset 11"
.....
 time="2020-10-08 03:04:25" level=debug msg="Cleaning log /var/lib/liftbridge/streams/test-stream2/0 based on retention policy {Bytes:0 Messages:0 Age:1h0m0s}"
 time="2020-10-08 03:04:25" level=debug msg="Finished cleaning log /var/lib/liftbridge/streams/test-stream2/0"
time="2020-10-08 03:04:25" level=debug msg="Removed earliest 0 entries from leader epoch cache based on passed offset 11 leaving 1 in epoch file for log [subject=test-stream2, stream=test-stre
```

Drop subscriber and start it again we get error:

```
 time="2020-10-08 04:24:18" level=debug msg="api: Subscribe [stream=test-stream2, partition=0, start=OFFSET, offset=0, timestamp=0]"
time="2020-10-08 04:24:18" level=error msg="api: Failed to subscribe to partition [subject=test-stream2, stream=test-stream2, partition=0]: rpc error: code = Internal desc = Failed to create stream reader: entry not found"
```
Metadata:

```
  ## Name: test-stream2 Subject: test-stream2
    ### Partition: 0
    Leader        : dstage-db
    Replicas      : dstage-db
    ISR           : dstage-db
    HighWatermark : 10
    NewestOffset  : 10
```

I suspect **Retention policy** affected this. When I disable it, errors not happen:

```
streams:
    compact.enabled: true
    retention.max:
        age: 0

```

**Comment by tylertreat** [comment]
@aversant I have reproduced this behavior. Looking into the issue...

**Comment by tylertreat** [comment]
This has been addressed in #271.

**Comment by aversant** [comment]
> 
> 
> This has been addressed in #271.

Very thanks! The trouble is gone.
